feat: prevent from adding new variables
arikchakma/maily.to pull request #86
Opened 2024-12-14 11:28 UTC by arikchakma

2024-12-16 08:25 UTC, SokratisVidros approved these changes

2024-12-16 09:35 UTC, SokratisVidros commented on packages/core/src/editor/components/ui/input-autocomplete.tsx
> +    if (
@arikchakma and I discussed about this offline. We will also use a render function to control which variables should appear in the autocomplete as the user types to make it more powerful.

2024-12-16 09:36 UTC, SokratisVidros requested changes
This PR needs the addition of a render function to control whether each autosuggested variable is visible to the list or not as the user types.

2024-12-16 20:34 UTC, SokratisVidros requested changes

2024-12-16 20:34 UTC, SokratisVidros commented on packages/core/src/editor/components/for-menu/for-bubble-menu.tsx
> +      block: {
Do we have the actual block object, and pass that to the callback function instead of passing a mocked one?

2024-12-16 20:34 UTC, SokratisVidros commented on packages/core/src/editor/components/for-menu/for-bubble-menu.tsx
> +    if (Array.isArray(variables)) {
I would suggest you do this processing in one place, not in each bubble menu that requires variables.

2024-12-16 20:34 UTC, SokratisVidros commented on packages/core/src/editor/components/for-menu/for-bubble-menu.tsx
> +    return variables({
Please check if typeof variables === 'function'. Then on anything else, throw a run time error about invalid variables property.

2024-12-16 20:40 UTC, SokratisVidros commented
@arikchakma reminder to update the readme ;)

2024-12-16 20:41 UTC, arikchakma commented
> @arikchakma reminder to update the readme ;)

Sure

2024-12-17 06:31 UTC, SokratisVidros approved these changes

2024-12-17 06:31 UTC, SokratisVidros commented on packages/core/readme.md
> +     triggerSuggestionCharacter="@"
Will you apply this renaming in this or in a follow up PR?

2024-12-17 16:39 UTC, desiprisg approved these changes

2024-12-17 21:08 UTC, merged